version: '3'

services:
  programmers-home:
    image: node:lts
    user: node
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - client_node_modules:/app/client/node_modules
      - server_node_modules:/app/api-server/node_modules
      - cli_node_modules:/app/cli/node_modules
    working_dir: /app
      
  api-server:
    image: node:lts
    user: node
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - MONGODB_URL=mongodb://db:27017/programmers_home
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - client_node_modules:/app/client/node_modules
      - server_node_modules:/app/api-server/node_modules
      - cli_node_modules:/app/cli/node_modules
    working_dir: /app/api-server
    command: npm run dev
    ports: 
      - '3000:3000'

  client:
    image: node:lts
    user: node
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - client_node_modules:/app/client/node_modules
      - server_node_modules:/app/api-server/node_modules
      - cli_node_modules:/app/cli/node_modules
    working_dir: /app/client
    command: npm run dev
    ports: 
      - '8000:1234'

  cli:
    image: node:lts
    user: node
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - client_node_modules:/app/client/node_modules
      - server_node_modules:/app/api-server/node_modules
      - cli_node_modules:/app/cli/node_modules
    working_dir: /app/cli
    command: npm run dev
    ports: 
      - '1212:1212'

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db

volumes:
  node_modules:
  client_node_modules:
  server_node_modules:
  cli_node_modules:
  db:

